In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# arange(start,stop,step)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
# number of rows/number of columns
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace

In [22]:
# return evenly spaced numbers over specified intervals
# start, stop, number of points
# differs from .arange()
# one dimensional array
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

#### create an identity matrix
a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros. The effect of multiplying a given matrix by an identity matrix is to leave the given matrix unchanged. Useful for linear algebra.

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# populated with random samples from a uniform distribution from zero to one
#  one dimensional array, uniformly distributed 
np.random.rand(5)

array([0.28135041, 0.59972381, 0.42866865, 0.21971535, 0.60489647])

In [27]:
# two dimensional
np.random.rand(5,5)

array([[0.59083509, 0.0429514 , 0.71894156, 0.15270328, 0.82175582],
       [0.2897969 , 0.15638097, 0.45361519, 0.6230619 , 0.47671718],
       [0.04450556, 0.4749537 , 0.96679898, 0.04650152, 0.88174407],
       [0.39446601, 0.33710712, 0.94866921, 0.5166384 , 0.34198797],
       [0.2804827 , 0.2199651 , 0.09373854, 0.13365651, 0.31020772]])

In [29]:
# return samples from a standard normal (gaussian) distribution centered around 0, use randn
# one dimensional
np.random.randn(5)

array([ 1.61788636, -0.53967548,  0.8546746 , -0.15346702, -1.44269765])

In [30]:
# two dimensional
np.random.randn(5,5)

array([[ 1.23275595, -0.80806667, -1.00373642,  0.25507502, -3.17725747],
       [-0.25173916, -1.09664346,  0.01221619,  1.32630888, -0.94107534],
       [ 0.43515414,  0.43503903,  0.58884828, -0.98516925,  0.89037651],
       [-0.38059583,  0.16340673, -0.36964091, -0.34444602, -1.1499933 ],
       [-1.39077004, -0.71962973, -2.64032761,  1.32890856,  0.13001839]])

In [38]:
# randint - generate random integers with a ceiling
# randint(low, high=None, size=None, dtype='l')
np.random.randint(1024)

863

In [39]:
# generate 10 numbers between 1 and 1024
np.random.randint(1,1024,10)

array([806, 811, 796, 853, 349, 356, 388, 782, 456, 764])

In [64]:
# 
np.random.randint(10,1024,10)

array([323, 466, 144, 155,  59, 664, 111, 196, 244, 424])

In [65]:
arr = np.arange(25)

In [44]:
randarr = np.random.randint(0,50,10)
randarr

array([41, 31,  6,  3, 22, 29, 41, 27, 39, 41])

In [66]:
# reshape - return the data with a new shape
# reshape the 25 item array into 5x5
# will error out if it doesn't divide evenly
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
randarr

array([41, 31,  6,  3, 22, 29, 41, 27, 39, 41])

In [50]:
# find the max
randarr.max()

41

In [51]:
randarr.min()

3

In [54]:
# which index does the max have
randarr.argmax()

0

In [55]:
# which index does the min have?
randarr.argmin()

3

In [67]:
# describe the shape of the data
arr.shape

(25,)

In [71]:
# reshape the array and check the shape
arr = arr.reshape(5,5)

In [72]:
arr.shape

(5, 5)

In [74]:
arr.dtype

dtype('int64')

In [78]:
# importing specific modules
from numpy.random import randint

### Latex Expressions

$e^{i\pi} + 1 = 0$

$$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[:3]


array([0, 1, 2])

In [5]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[3:9]

array([3, 4, 5, 6, 7, 8])

In [14]:
arr[3:9:]

array([3, 4, 5, 6, 7, 8])

In [17]:
# expected this to reverse the entries
arr[3:9:-1]

array([], dtype=int64)

In [18]:
arr[8 - 1]

7

In [21]:
# changing the values of multiple variables
arr[0:5] = 100

In [22]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
# also supports tuple unpacking
arr[0:3]= 10,20,30
arr

array([ 10,  20,  30, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr

array([ 10,  20,  30, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
slice_of_arr = arr[0:6]

In [30]:
slice_of_arr

array([ 10,  20,  30, 100, 100,   5])

In [32]:
slice_of_arr[:] = 99

In [34]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [37]:
# when we ran slice_of_arr = arr, we didn't copy it - it was a view (or a reference)
# so changes were made to the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
# to specify a copy:

In [39]:
arr_copy = arr.copy()

In [40]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_copy[3:6] = 666

In [44]:
# copy is changed
arr_copy

array([ 99,  99,  99, 666, 666, 666,   6,   7,   8,   9,  10])

In [45]:
# array remains the same
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Nested List

In [48]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d.shape

(3, 3)

In [51]:
# Two formats for grabbing arrays from a matrix:
# double bracket format and single bracket format with comma
# Double Bracket
# getting the 5
arr_2d[0][0]

5

In [54]:
# or getting the 30
arr_2d[1][2]

30

In [55]:
# Using the row comma notation
arr_2d[1,2]

30

In [57]:
# using slicing 
# grabbing multiple values
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
# get the first two nested arrays (everything before [2])
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [61]:
# get [1]
arr_2d[1:2]

array([[20, 25, 30]])

In [64]:
# get arr2, cols 1 and 2 (vals 20 and 25)
arr_2d[1:2,:2]

array([[20, 25]])

#### compare array and get booleans as comparison operators

In [66]:
# New array
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# Show me the entire array and whether the values are above 5
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [72]:
# in one step:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [74]:
# All the slements less than 3
arr[arr < 3]

array([1, 2])

#### Exercise

In [76]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])